version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/escola
    depends_on:
      db:
        condition: service_healthy  # ✅ Aguarda o PostgreSQL estar pronto

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: escola
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # ✅ Verifica se o banco está pronto
      test: ["CMD-SHELL", "pg_isready -U admin -d escola"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
